// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPages.Data.Concreate.EfCore;

#nullable disable

namespace RazorPages.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240707014757_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RazorPages.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departmant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departmant = "It",
                            Email = "mertclkdev@gmail.com",
                            Name = "Mert Çalık",
                            Photo = "mert.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Departmant = "Security",
                            Email = "casper@gmail.com",
                            Name = "Casper",
                            Photo = "casper.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Departmant = "Witcher",
                            Email = "cirilla@gmail.com",
                            Name = "Princess Cirilla",
                            Photo = "ciri.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Departmant = "Witcher",
                            Email = "geralt@gmail.com",
                            Name = "Geralt of Rivia",
                            Photo = "geralt.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
